---
title: "Adapting Virtual Reality Training Applications"
subtitle: "by Fabio Genz and Dieter Kranzlmüller"
author: "Arsine Chinaryan, Anh Hoang Minh Dang, Iris Dizdari, Margarita Khachatryan"
institute: "Supervisor: Daniel Schlichting"
date: "2024-2-13"
format: 
  revealjs:
    css: customstyle.css
    embed-resources: true
    slide-number: true
    logo: "LMULogo.jpg"
editor: visual
---

## Outline

::: incremental
1.    Overview & Terminology

2.    Data analysis

        Relationship between percieved Stress and Physical Meassurements\
        Relationship over the Rounds\
        Subgroup Behavior\
        Cohort Comparison

3.    Summary and Discussion
:::

## Overview

### 

**VR-Training**: Adapting Virtual Reality Training Applications by Dynamically Adjusting Visual Aspects\

::: incremental
-   **Survey**: Cross-sectional Study with Longitudinal Elements

-   2 Cohorts (Linne and Dame) 
 
    --    21 Participants in Linne, 81 in Dame (with overlaps)
 
    --    9 Rounds of Training for Dame and 11 for Linne
    
    --    Grouped into Adative and Non-Adaptive Training versions
    
    --    2 Rounds of Test per Cohort (Linne: VR, Dame: Real-world)

-   **Timeframe**: 
:::

## Terminology

###

-   **Q1**: Percieved cognitive Load 
-   **Q2**: Percieved physical Load
-   



## Outline

[1. Overview & Terminology]{style="color:lightgray;"}

2.  Data Analysis

    Relationship between percieved Stress and Physical Meassurements\
    [Relationship over the Rounds]{style="color:lightgray;"}\
    [Subgroup Behavior]{style="color:lightgray;"}\
    [Cohort Comparison]{style="color:lightgray;"}

[3. Summary and Discussion]{style="color:lightgray;"}